# Generated by Django 3.0.3 on 2020-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("website", "0002_account_groups")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
