# Generated by Django 3.0.3 on 2020-06-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("website", "0003_auto_20200603_1810")]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="tag", to="website.Tag"),
        ),
    ]
