# Generated by Django 3.0.3 on 2020-05-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("website", "0003_auto_20200516_2342")]

    operations = [migrations.RemoveField(model_name="post", name="to_read")]
