# Generated by Django 3.0.3 on 2020-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("website", "0004_auto_20200606_1107")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="post_tag", to="website.Tag"),
        )
    ]
