# Generated by Django 3.0.3 on 2020-05-30 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_post_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='archive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Archive'),
        ),
    ]
